### ISSUE TITLE
Change "Website Name" in privacy.md to "FeminineBoy.net"

### ISSUE THREAD

**Issue by genericusername3** [Feuerhamster/feminineboy#1]
In the section "Children's Information" of `content/privacy.md`, the second paragraph starts with "Website Name". I guess this might have just been overlooked when modifying the template, so it should probably replaced with "FeminineBoy.net"

**Comment by genericusername3** [comment]
Also, I think the mailto link at the bottom should contain the email adress on its label, but I'm not sure which one is the correct email address.

Going with contact@feminineboy.net for my pull request, #2.

**Comment by Feuerhamster** [comment]
Thanks for your help 👍
I've merged your pull request.
The email address is theoretically irrelevant, because every mailbox name of the domain can receive emails, but your change is fine.
